[package]
name = "excel_operation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "excel_operation"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
calamine = "0.21"
